### PR TITLE
Allow setting the generated VMDK's flat filename

### PR DESCRIPTION
**Pull request by mikem2005**

### CODE REVIEW

**Comment by Zapotek** [comment]
So this basically allows a user to optionally specify his own imgLocation in the VMDK file, right?
Why would the image location differ from the location of the raw image?

**Comment by mikem2005** [comment]
This is useful if you want to normalize the filename.  If you're accepting the original RAW filename as input from the user, it may or may not have an .img extension.  This change allows the system to assign a useful, consistent filename like "scsi02-flat.vmdk".

**Comment by Zapotek** [comment]
OK, I'm really pressed for time so it's gonna take me a while to test an accept the pull request.
Thanks for the code. :)

**Comment by mikem2005** [comment]
Thanks Zapotek!

**Comment by Zapotek** [comment]
Really sorry it took me so long. I was very preoccupied with uni and
Arachni that it tottaly slipped my mind.
On Oct 31, 2011 6:08 PM, "Mike Matczynski" <
reply@reply.github.com>
wrote:

**Pull request merged**
